-- ============================================================================
-- Meteoro 24 — actualizar o corpo dos serviços (texto mais enxuto)
-- Colar no phpMyAdmin. Actualiza só a coluna body, por slug e idioma.
-- ============================================================================

SET NAMES utf8mb4;

UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["Estruturamos a obra antes de ela começar e mantemos esse plano vivo enquanto decorre. O objectivo não é produzir um cronograma bonito, mas ter, a qualquer momento, uma resposta fundamentada para \\"onde estamos\\" e \\"o que acontece a seguir\\"."]' WHERE s.slug = 'planeamento-e-controlo-de-obras' AND st.locale = 'pt';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["Um orçamento serve para decidir, não apenas para aprovar. Por isso trabalhamos a partir de quantidades medidas e de pressupostos explícitos — quem lê o orçamento percebe de onde vem cada valor e o que muda se a solução mudar."]' WHERE s.slug = 'orcamentacao' AND st.locale = 'pt';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["A fiscalização representa o interesse de quem paga a obra. Verificamos o que está a ser executado contra o que foi contratado e registamos o que encontramos, para que as decisões fiquem documentadas e não dependam de memória."]' WHERE s.slug = 'fiscalizacao' AND st.locale = 'pt';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["Um edifício degrada-se de forma previsível. Tratar a degradação cedo, segundo um plano, custa uma fracção do que custa reagir a uma patologia já instalada."]' WHERE s.slug = 'reforma-e-manutencao' AND st.locale = 'pt';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["Numa estrutura metálica, o erro não se corrige com argamassa. A coordenação entre desenho, fabrico e montagem é o que separa uma estrutura que assenta à primeira de uma que consome semanas em ajustes."]' WHERE s.slug = 'estruturas-metalicas' AND st.locale = 'pt';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["Uma piscina é uma obra de engenharia com acabamento à vista. Estrutura, impermeabilização, hidráulica e revestimento têm de ser decididos em conjunto — é aí que se ganha ou perde a durabilidade."]' WHERE s.slug = 'piscinas' AND st.locale = 'pt';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["We structure the build before it starts and keep that plan alive while it runs. The aim is not a good-looking programme, but a defensible answer, at any moment, to \\"where are we\\" and \\"what happens next\\"."]' WHERE s.slug = 'planeamento-e-controlo-de-obras' AND st.locale = 'en';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["A budget exists to support a decision, not just to be approved. We work from measured quantities and stated assumptions, so whoever reads the estimate can see where each figure comes from and what changes if the solution changes."]' WHERE s.slug = 'orcamentacao' AND st.locale = 'en';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["Supervision represents the interest of whoever is paying for the build. We verify what is being executed against what was contracted and record what we find, so decisions are documented rather than remembered."]' WHERE s.slug = 'fiscalizacao' AND st.locale = 'en';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["A building deteriorates predictably. Treating that deterioration early, to a plan, costs a fraction of reacting to a defect that has already taken hold."]' WHERE s.slug = 'reforma-e-manutencao' AND st.locale = 'en';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["In a steel structure, an error cannot be corrected with mortar. Coordination between design, fabrication and erection is what separates a frame that fits first time from one that consumes weeks in adjustments."]' WHERE s.slug = 'estruturas-metalicas' AND st.locale = 'en';
UPDATE `service_translations` st JOIN `services` s ON s.id = st.service_id SET st.body = '["A pool is an engineering work with an exposed finish. Structure, waterproofing, hydraulics and finishes have to be decided together — that is where durability is won or lost."]' WHERE s.slug = 'piscinas' AND st.locale = 'en';
